CREATE DATABASE IF NOT EXISTS BTC;

ALTER SCHEMA `BTC`  DEFAULT CHARACTER SET utf8mb4  DEFAULT COLLATE utf8mb4_general_ci ;
USE BTC;

CREATE TABLE BTCBRL (
    name VARCHAR(255),
    pctChange VARCHAR(255),
    create_date DATETIME
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;